- package.json
- src/common/pageManagers/twitterPageManager.js
- src/common/tipping/Tipping.js
- src/common/tipping/tippingUnregistered.js
- yarn.lock
- Add icon for unregistered users
- Redirect to /send instead of /tip
> feat: add idriss send support

- src/application/snapshot/app.tsx
- src/application/tally/app.tsx
- added keys to organization containers
> fix-tally-widget-not-showing-on-direct-profile-change

- .gitignore
- src/application/gitcoin/commands/get-gitcoin-across-chain-fees.ts
- src/application/gitcoin/constants.ts
- src/application/gitcoin/hooks/use-across-donate-transaction.ts
- src/application/gitcoin/hooks/use-donate-transaction.ts
- src/application/gitcoin/hooks/use-donation-maker.ts
- src/application/gitcoin/utils.ts
- src/runtime/chromium/manifest.json
- src/shared/web3/constants.ts
- add calldata to crosschain donations
- fix data types
- add manual gasLimit
- fix chainId for nonce calculation
- temp. remove icons from manifest
> Fix crosschain donations

- src/application/agora/commands/get-agora-proposals.ts
- src/application/agora/constants.ts
- src/application/agora/schema.ts
- src/application/agora/types.ts
- src/application/agora/utils.ts
- src/application/agora/widgets/proposal-handle.container.tsx
- src/application/agora/widgets/proposal-main.container.tsx
- src/application/agora/widgets/proposal.tsx
- src/runtime/chromium/manifest.json
https://github.com/user-attachments/assets/c524ab01-7598-480a-96fc-419e8ee2f0fb
> agora api adjustments

- src/shared/ui/components/widget-tab/widget-tab.component.tsx
> fixed overlapping pixels

- src/infrastructure/content-script/content-script.ts
- src/shared/extension/extension-settings-manager.ts
- src/shared/web3/context/wallet.tsx
- src/shared/web3/storage.ts
fixes discord issue
https://github.com/user-attachments/assets/a28b2170-43bf-4b03-89b4-7e2dcdd3351e
> Migrate local storage to chrome storage

- src/shared/messaging/command.ts
fixes one of the sentry issues, I am not sure how exactly is it happening so for now this just hides runtime error
> fix: in on undefined

- apps/extension/src/application/gitcoin/widgets/donation-widget.tsx
- apps/extension/src/application/idriss-send/components/send-widget.tsx
- apps/extension/src/shared/idriss/components/send/container.tsx
- apps/extension/src/shared/idriss/components/send/form.tsx
- apps/extension/src/shared/idriss/components/send/heading.tsx
- apps/extension/src/shared/idriss/constants.ts
- packages/ui/src/components/modal/backdrop.tsx
- packages/ui/src/components/modal/modal.tsx
- packages/ui/src/components/wallet-connect-modal/wallet-connect-modal.tsx
https://github.com/user-attachments/assets/d1bbbacb-402e-4a6a-9baf-09a82f3e29b1
> feat: reuse modal from design system

- packages/ui/package.json
- packages/ui/src/components/button/button.tsx
- packages/ui/src/components/button/glow.tsx
- packages/ui/src/components/button/variants.ts
- packages/ui/src/components/spinner/index.ts
- packages/ui/src/components/spinner/spinner.tsx
https://github.com/user-attachments/assets/21c7da60-45d1-4fac-8605-ff4b30189992
> added button loading state

- apps/main-landing/src/components/products-section/components/product-info/product-info.tsx
- apps/main-landing/src/components/products-section/components/product-section.tsx
https://github.com/user-attachments/assets/e8d0b8aa-15a3-4dd8-8081-818ce46709e4
> fixed short narrow screens

- apps/main-landing/src/components/image-sequencer/image-sequencer.tsx
- apps/main-landing/src/components/token-section/token-section.tsx
> made token section wider

- apps/main-landing/src/components/products-section/components/creators-section/creators-section-data.tsx
- apps/main-landing/src/components/products-section/components/desktop-products-section.tsx
- apps/main-landing/src/components/products-section/components/extension-section/extension-section-data.tsx
- apps/main-landing/src/components/products-section/components/mobile-products-section.tsx
- apps/main-landing/src/components/products-section/components/prediction-markets-section/prediction-markets-section-actions.tsx
- apps/main-landing/src/components/products-section/components/prediction-markets-section/prediction-markets-section-data.tsx
- apps/main-landing/src/components/products-section/constants.ts
- apps/main-landing/src/constants.ts
- change paths for product sections
> - change wording of prediction market waitlist

- apps/main-landing/src/components/products-section/components/mobile-products-section.tsx
- apps/main-landing/src/components/products-section/components/product-section.tsx
- apps/main-landing/src/components/products-section/products-section.tsx
https://github.com/user-attachments/assets/c2b673e7-21be-49c5-bc28-14512882072d
> fixed mobile url anchor scroll & 1536x760 res

- apps/extension/src/application/trading-copilot/subscriptions-management/components/subscription-form.tsx
- apps/extension/src/application/trading-copilot/subscriptions-management/components/subscriptions-list/subscription-item.tsx
- apps/extension/src/application/trading-copilot/subscriptions-management/components/subscriptions-list/subscription-list.types.ts
- apps/extension/src/application/trading-copilot/subscriptions-management/subscriptions-management.tsx
- apps/extension/src/application/trading-copilot/types.ts
Add handling of displaying socials badges in subscriptions list
> feat: fetch socials of farcaster accounts

- apps/main-landing/src/components/token-section/components/token-sale-countdown.tsx
- removed token sale countdown timer, instead display SOLD OUT
> feat: update token sale countdown timer to display sold out

- apps/extension/src/infrastructure/service-worker/service-worker.ts
- apps/extension/src/runtime/chromium/manifest.json
- apps/extension/src/runtime/firefox/manifest.json
Added manually injection of extension code during first installation if not injected yet.
> feat: inject extension manually after installation

- apps/copilot-api/services/subscriptionManager.ts
Co-authored-by: SolutionsEngineer <106707979+SolutionsEngineer@users.noreply.github.com>
Co-authored-by: Mateusz Stawski <100126546+MateuszStawski@users.noreply.github.com>
Co-authored-by: Levertz <95511599+lennardevertz@users.noreply.github.com>
> feat(copilot): introduce redesign to trading copilot (#167)

- apps/extension/src/shared/ui/components/select/select-option.component.tsx
- apps/main-landing/src/app/creators/donate/components/select/select-option.component.tsx
Updated margin and padding sizes to match perfectly figma designs
> fix: update select classes to match figma design

- apps/copilot-api/entities/subscribtions.entity.ts
- apps/copilot-api/routes/index.ts
- apps/copilot-api/routes/subscribtions.ts
- apps/copilot-api/services/subscriptionManager.ts
- apps/extension/src/application/trading-copilot/commands/constants.ts
- apps/extension/src/application/trading-copilot/hooks/use-login-via-siwe.ts
- apps/extension/src/application/trading-copilot/index.ts
- apps/extension/src/application/trading-copilot/subscriptions-management/components/subscription-form.tsx
- apps/extension/src/application/trading-copilot/subscriptions-management/components/subscription-form.types.ts
- apps/extension/src/application/trading-copilot/subscriptions-management/components/subscriptions-list/subscription-item.tsx
- apps/extension/src/application/trading-copilot/subscriptions-management/components/subscriptions-list/subscription-list.types.ts
- apps/extension/src/application/trading-copilot/subscriptions-management/components/subscriptions-list/subscriptions-list.tsx
- apps/extension/src/application/trading-copilot/subscriptions-management/subscriptions-management.tsx
- apps/extension/src/application/trading-copilot/types.ts
- apps/extension/src/final/widgets/follow-trading-copilot.tsx
- apps/extension/src/infrastructure/service-worker/service-worker.ts
- packages/tailwind-config/tailwind.config.mjs
Added FID handling in BE and FE. Removed storing farcaster details in localStorage.
warning: we need to update API asap after merging this PR due to variable name changes, which will crash whole trading copilot tab until updating API to return new response
(Mentioned API: https://copilot-production-e887.up.railway.app)
> feat: add fid handling in BE and FE

- apps/extension/src/final/notifications-popup/components/trading-copilot-dialog/trading-copilot-dialog.tsx
- apps/extension/src/final/notifications-popup/components/trading-copilot-toast/trading-copilot-toast.tsx
- apps/extension/src/final/notifications-popup/components/trading-copilot-toast/trading-copilot-toast.types.ts
- apps/extension/src/final/notifications-popup/notifications-popup.tsx
- apps/extension/src/shared/utils/index.ts
- apps/extension/src/shared/utils/wallet-utils.ts
Added preload of ensName and ensAvatar before displaying toast. 
Fixed disabled state for BUY button in modal.
> feat: preload name and pfp before displaying toast

- apps/extension/src/final/notifications-popup/notifications-popup.tsx
- prevent multiple notification sounds from playing within a 1-second window by introducing a debounce mechanism
- ensure only one sound instance is played at a time, even for rapid successive notifications
- reuse the audio instance for subsequent notifications and reset after playback finishes
> fix: notification sound stacking issue

- apps/extension/src/application/trading-copilot/subscriptions-management/components/subscriptions-list/subscription-item.tsx
- apps/extension/src/application/trading-copilot/subscriptions-management/components/subscriptions-list/subscription-list.types.ts
- apps/extension/src/application/trading-copilot/subscriptions-management/components/subscriptions-list/subscriptions-list.tsx
- replaced trash with x icon for removing subscriptions
- displayed ens name or address (if no ens name resolved) initially
- aligned icon for remove subscriptions with notification sound toggle
https://github.com/user-attachments/assets/47b942ca-cae1-4e46-8a77-fef3299dc759
> feat: improve ux of adding copilot subscriptions

- apps/extension/src/final/notifications-popup/components/trading-copilot-toast/trading-copilot-toast.tsx
- apps/extension/src/final/notifications-popup/components/trading-copilot-toast/trading-copilot-toast.types.ts
- apps/extension/src/final/notifications-popup/notifications-popup.tsx
- apps/extension/src/final/notifications-popup/notifications-popup.types.ts
- apps/extension/src/infrastructure/application/application.tsx
- apps/extension/src/shared/ui/components/index.ts
- apps/extension/src/shared/ui/components/preloaded-image/index.ts
- apps/extension/src/shared/ui/components/preloaded-image/preloaded-image.component.tsx
- apps/extension/src/shared/ui/index.ts
Added preload to image in copilot notification, now we fetch it before displaying notification.
> feat: add preload of avatar image in copilot notification

- apps/extension/src/application/trading-copilot/subscriptions-management/components/subscriptions-list/subscriptions-list.tsx
Changed the ScrollArea imported from radix to the one imported from @idriss-xyz/ui/scroll-area, which is the correct one for our design system.
> style(copilot): Change scrollbar to design system on suscription list

- apps/extension/src/application/trading-copilot/commands/constants.ts
- apps/extension/src/application/trading-copilot/commands/get-trading-copilot-subscriptions.ts
- updated COPILOT_API_URL to the most recent production one
- aligned imports for COPILOT_API_URL throughout the whole repo
> feat: update copilot api url

- apps/extension/src/application/trading-copilot/commands/get-quote.ts
- apps/extension/src/application/trading-copilot/hooks/use-exchanger.ts
- apps/extension/src/application/trading-copilot/types.ts
- apps/extension/src/final/notifications-popup/components/trading-copilot-dialog/trading-copilot-dialog.tsx
Change localStorage to new extension storage
> Fix: Adding auth token to get-quote API call (fixes unauthorized requests to quote endpoint).

- apps/extension/src/application/trading-copilot/subscriptions-management/components/subscriptions-list/subscription-item.tsx
- apps/extension/src/application/trading-copilot/subscriptions-management/components/subscriptions-list/subscription-list.types.ts
- apps/extension/src/shared/ui/components/lazy-image/lazy-image.component.tsx
- improved copilot subscriptions loading state
- enhanced lazy image component while maintaining backward compatibility
https://github.com/user-attachments/assets/addf8037-835e-4a1f-96f5-b0ba871d09b1
> fix: improve copilot subscriptions loading state

- packages/wallet-connect/src/context.tsx
Changed code to dont ask to login every time after closing browser.
Added updating wallet state between tabs.
> feat: dont ask to login after closing browser

- apps/extension/src/application/trading-copilot/subscriptions-management/subscriptions-management.tsx
- apps/extension/src/final/notifications-popup/components/trading-copilot-dialog/trading-copilot-dialog.tsx
- apps/extension/src/final/notifications-popup/components/trading-copilot-dialog/trading-copilot-dialog.types.ts
- apps/extension/src/shared/extension/context/auth-token-context.tsx
Updated TradingCopilotTradeValue component to use latest authToken from context storage.
> fix: use latest authToken in trading copilot trade value component

- apps/extension/src/application/trading-copilot/hooks/use-login-via-siwe.ts
- packages/wallet-connect/src/context.tsx
Added prompt to authorize website if currently wallet is not authorized on this website.
> fix: added prompt to authorize website before login via siwe

- apps/extension/src/application/trading-copilot/hooks/use-exchanger.ts
Added verification if wallet provider is authorized before using exchanger, and added authorize popup when unauthorized.
> fix: copilot exchanger authorization

- apps/extension/src/application/gitcoin/widgets/donation-widget.tsx
- apps/extension/src/application/idriss-send/components/send-widget.tsx
- apps/extension/src/application/polymarket/hooks/use-is-usdc-allowed.ts
- apps/extension/src/application/polymarket/hooks/use-post-order.ts
- apps/extension/src/application/polymarket/hooks/use-safe-wallet.ts
- apps/extension/src/application/polymarket/hooks/use-user.ts
- apps/extension/src/application/trading-copilot/hooks/use-exchanger.ts
- apps/extension/src/application/trading-copilot/hooks/use-login-via-siwe.ts
- apps/extension/src/application/trading-copilot/subscriptions-management/components/subscription-form.tsx
- apps/extension/src/application/trading-copilot/subscriptions-management/components/subscriptions-list/subscription-item.tsx
- apps/extension/src/application/trading-copilot/subscriptions-management/subscriptions-management.tsx
- apps/extension/src/final/extension-popup/components/top-bar/navigation.tsx
- apps/extension/src/final/notifications-popup/components/trading-copilot-dialog/trading-copilot-dialog.tsx
- apps/extension/src/final/widgets/follow-trading-copilot.tsx
- apps/extension/src/infrastructure/application/providers.tsx
- apps/extension/src/shared/extension/context/index.ts
- apps/extension/src/shared/extension/context/wallet-context.tsx
- apps/extension/src/shared/extension/index.ts
- packages/wallet-connect/src/index.ts
Moved wallet context provider due to increasing complexity due to extension features which aren't needed on main-landing.
Added authToken remover when wallet removed.
> feat: move wallet context to extension & remove authToken when wallet removed

- apps/extension/src/application/trading-copilot/commands/index.ts
- apps/extension/src/application/trading-copilot/commands/verify-token.ts
- apps/extension/src/application/trading-copilot/hooks/use-login-via-siwe.ts
- apps/extension/src/application/trading-copilot/types.ts
Added verification if token is outdated using API /verify-token endpoint.
> feat: added auth token verification

- apps/extension/src/application/trading-copilot/subscriptions-management/subscriptions-management.tsx
- apps/extension/src/final/extension-popup/components/top-bar/navigation.tsx
- apps/extension/src/final/notifications-popup/components/trading-copilot-dialog/trading-copilot-dialog.tsx
- packages/ui/src/components/icon/constants.ts
> Revert "Security policies"

- apps/extension/src/application/trading-copilot/commands/get-quote.ts
- apps/extension/src/application/trading-copilot/hooks/use-exchanger.ts
- apps/extension/src/application/trading-copilot/types.ts
- apps/extension/src/final/notifications-popup/components/trading-copilot-dialog/trading-copilot-dialog.tsx
As in title, removed unused authToken and now we send fetch without authorization.
> refactor: remove unsused authToken in get-quote

- apps/extension/src/host/twitter/hooks/use-handle-to-username-map.ts
Added one fix that was previously on master (did not bring master commits into copilot-dev, not merged).
>  fix: Repeated requests to dao-twitter-handles endpoint

- apps/extension/src/application/trading-copilot/hooks/use-subscriptions.ts
- apps/extension/src/infrastructure/application/providers.tsx
- apps/extension/src/infrastructure/content-script/content-script.ts
- apps/extension/src/infrastructure/service-worker/service-worker.ts
- apps/extension/src/shared/extension/context/trading-copilot-context.tsx
- apps/extension/src/shared/extension/context/wallet-context.tsx
- apps/extension/src/shared/extension/index.ts
- apps/extension/src/shared/extension/trading-copilot-manager.ts
- apps/extension/src/shared/extension/types.ts
- apps/extension/src/shared/web3/index.ts
- apps/extension/src/shared/web3/storage.ts
Added subscriptions amount storage in extension memory to connect websocket only if user have subscriptions.
After loging in without subscriptions:
After subscribing:
After unsubscribing:
After loging in with subscriptions:
> feat(draft): connect websocket only if user have subscriptions

- apps/main-landing/src/app/claim/components/vesting-plan/vesting-plan-content.tsx
- apps/main-landing/src/app/vault/components/unstake-tab-content.tsx
- fix formatting on token amount
- removed $ in all modals from claim and vault
- update modal wording depending on vesting plan
> fix: minor UI updates

- apps/main-landing/src/app/vault/components/unstake-tab-content.tsx
- removed one more dollar sign from unstaking loading modal
> fix: removed one more dollar sign from unstaking modal

- apps/main-landing/next.config.ts
- added redirect from https://idriss.xyz/retroactive-distribution to https://docs.idriss.xyz/idriss-token/retroactive-distribution
> feat: added retroactive-distribution redirect to our docs

- apps/main-landing/src/app/claim/components/vesting-plan/vesting-plan-content.tsx
https://github.com/user-attachments/assets/035ac590-0635-414a-9544-4a42a3dacaeb
> added wallet ownership check

- apps/main-landing/src/components/top-bar/components/mobile/mobile.tsx
Maybe EXTERNAL_LINK was not the right name for this and could be changed for APP_LINKS and include /creators (instead of current INTERNAL_LINKS that fo to /# sections of main page).
> feat: Add vault menu item on mobile

- apps/main-landing/src/app/creators/obs/components/donation-notification.tsx
- apps/main-landing/src/app/creators/obs/utils.ts
- this safeguard prevents donations with price displayed as NaN or undefined, instead it will only display the donor's name or address
> fix: added a safeguard for donation price

- apps/extension/src/shared/extension/context/trading-copilot-context.tsx
- apps/extension/src/shared/messaging/command.ts
> fix: added retry delays in queries

- apps/extension/src/application/trading-copilot/hooks/use-subscriptions.ts
- apps/extension/src/application/trading-copilot/subscriptions-management/components/subscription-form.tsx
- apps/extension/src/final/extension-popup/components/trading-copilot-layout.tsx
- packages/constants/src/index.ts
- packages/constants/src/links.ts
- packages/ui/package.json
- packages/ui/src/components/badge/badge.tsx
- packages/ui/src/components/badge/index.ts
- packages/ui/src/components/badge/variants.ts
Added premium status badge and updated error message in subscribe form.
> feat: add premium status badge & update error message in subscribe form

- apps/main-landing/src/app/claim/components/letter/letter-content.tsx
- apps/main-landing/src/components/token-section/components/blocked-button.tsx
- packages/ui/src/components/icon/constants.ts
> feat: added claiming ended information

- apps/main-landing/src/app/creators/donate/components/donor-item.tsx
- apps/main-landing/src/app/creators/donate/components/history/donate-history-item.tsx
- apps/main-landing/src/app/creators/donate/constants.ts
- apps/main-landing/src/app/creators/donate/utils.ts
> feat: added block explorers in donate history

- apps/main-landing/src/app/page.tsx
- apps/main-landing/src/components/image-sequencer/image-sequencer.tsx
- apps/main-landing/src/components/products-section/components/desktop-products-section.tsx
Scroll block:
https://github.com/user-attachments/assets/2a8d3e1c-6afc-43c9-8fa9-29cabfd772e9
ImageSequencer optimization: (1st is original 2nd is optimized)
https://github.com/user-attachments/assets/2dbf889c-98da-45f1-8b3e-0a60da8ced5c
> added scroll block on products section change + refactored image sequencer to use canvas

- apps/main-landing/src/app/claim/components/claim/claim-content.tsx
- apps/main-landing/src/app/claim/components/claim/components/expandable-info.tsx
- apps/main-landing/src/app/claim/components/claim/components/idriss-user-criteria-description.tsx
- apps/main-landing/src/app/claim/components/letter/letter-content.tsx
> feat: reopen airdrop

- apps/main-landing/src/app/claim/desktop-content-manager.tsx
- apps/main-landing/src/app/claim/page.tsx
- packages/tailwind-config/tailwind.config.mjs
- packages/ui/package.json
- packages/ui/src/components/alert/alert.tsx
- packages/ui/src/components/alert/index.ts
- packages/ui/src/components/alert/variants.ts
- packages/ui/src/components/link/variants.ts
Added alert component to claim page.
> feat: add alert to claim page

- .gitignore
- apps/extension/src/application/trading-copilot/subscriptions-management/components/subscription-form.tsx
- apps/extension/src/application/trading-copilot/subscriptions-management/components/subscription-form.types.ts
- apps/extension/src/application/trading-copilot/subscriptions-management/components/subscriptions-list/subscription-item.tsx
- apps/extension/src/application/trading-copilot/subscriptions-management/components/subscriptions-list/subscription-list.types.ts
- apps/extension/src/application/trading-copilot/subscriptions-management/components/subscriptions-list/subscriptions-list.tsx
- apps/extension/src/application/trading-copilot/subscriptions-management/subscriptions-management.tsx
- apps/extension/src/application/trading-copilot/types.ts
fix: Await onSubmit calls in Farcaster name handling block
> fix: Prevent multiple onSubmit calls for Farcaster name submissions

- apps/extension/src/application/trading-copilot/hooks/use-login-via-siwe.ts
- apps/extension/src/final/notifications-popup/components/trading-copilot-dialog/trading-copilot-dialog.tsx
Removed unnecesary variable declarations (reduces memory consumption) and added one trycatch block for error handling of the siwe signing just in case. Also changed from isSending to isPending since it is more descriptive
> refactor: Cleaner code on siwe login hook

- .gitignore
- apps/main-landing/src/app/creators/donate/content.tsx
feat: Add useEffect to reset form defaults on chainId or tokenSymbol change
> Add default network and token selection useEffect

- apps/main-landing/src/app/creators/obs/components/donation-notification.tsx
- apps/main-landing/src/app/creators/obs/page.tsx
Added token details in obs toast.
> feat: display token details in obs toast

- apps/main-landing/src/app/creators/page.tsx
Updated styles to match figma designs.
> feat: update download banner link styles

- apps/main-landing/src/app/creators/donate/components/history/donate-history-item.tsx
- apps/main-landing/src/app/creators/obs/components/donation-notification.tsx
> fix: center token icon in donate history item

- apps/main-landing/src/components/products-section/components/prediction-markets-section/prediction-markets-section-actions.tsx
Changed error message to:
We couldn't add you to the waitlist. Try again later.
> fix: landing page form message

- apps/main-landing/src/app/creators/donate/commands/get-ens-avatar.ts
- apps/main-landing/src/app/creators/donate/constants.ts
> Revert "- update request url for relative usage"

- apps/main-landing/src/app/creators/donate/components/user-history/user-history-list.tsx
> fix: center token icon in user history

- apps/main-landing/src/app/api/claimed-events/[[...slug]]/route.ts
- apps/main-landing/src/app/vault/constants.ts
> Revert "- stop fetching claiming events"

- apps/main-landing/src/app/creators/donate/components/donor-item.tsx
- apps/main-landing/src/app/creators/donate/components/select/select-option.component.tsx
- apps/main-landing/src/app/creators/donate/components/select/select.component.tsx
- apps/main-landing/src/app/creators/donate/components/user-history/user-history-list.tsx
- apps/main-landing/src/app/creators/donate/content.tsx
- apps/main-landing/src/app/creators/donate/page.tsx
- apps/main-landing/src/app/creators/donate/top-donors.tsx
- packages/ui/src/components/form/field.tsx
- packages/ui/src/components/input/input.tsx
- packages/utils/src/index.ts
- packages/utils/src/utils.ts
> fix: updated styles to match designs in donate views

- packages/utils/src/utils.ts
> fix: amount rounding function

- apps/main-landing/src/app/creators/obs/components/donation-notification.tsx
Updated width of notification to automatically set width between 400 to 430px.
> feat: donation notification enlargement

- apps/main-landing/src/app/creators/donate/components/history/donate-history-item.tsx
- apps/main-landing/src/app/creators/donate/top-donors.tsx
Added scrollbar in top creators view, and changed amount of displayed creators from 6 to 20.
> feat: add scrollbar in top creators view

- apps/copilot-api/routes/auth.ts
- apps/copilot-api/services/auth.ts
- apps/copilot-api/services/subscriptionManager.ts
- apps/extension/src/final/notifications-popup/components/trading-copilot-dialog/trading-copilot-dialog.tsx
- apps/extension/src/final/notifications-popup/components/trading-copilot-dialog/trading-copilot-dialog.types.ts
- apps/extension/src/final/notifications-popup/notifications-popup.tsx
- apps/extension/src/final/notifications-popup/utils/token-icon.tsx
- apps/extension/src/infrastructure/service-worker/service-worker.ts
- apps/extension/src/shared/utils/index.ts
Includes fixes for:
- Farcaster name and avatar not showing on notification
- Farcaster name and avatar not on showing on trading-copilot-dialog
- Emptying subscription list prompts for siwe on first subscription again
- Error messages on subscribe/unsubscribe from extension (currently wip on separate branch, as it is a longer feature)
- Solana manual disconnect does not remove from extension storage [EDIT: not happening]
> Fix: Solana copilot minor bug fixes 

- apps/main-landing/next.config.ts
- apps/main-landing/src/app/creators/donate/components/donor-item.tsx
- apps/main-landing/src/app/creators/donate/components/donor-stats/donor-stats-list.tsx
- apps/main-landing/src/app/creators/donate/top-donors.tsx
> fix: hide border of last item in leaderboard list

- apps/main-landing/src/app/creators/donate/content.tsx
- apps/main-landing/src/app/creators/donate/hooks/use-sender.ts
> feat: add error message in tipping view

- apps/extension/src/final/widgets/follow-trading-copilot.tsx
> fix: render properly follow button in trading copilot widget

- apps/main-landing/src/app/creators/donate/components/donor-item.tsx
- apps/main-landing/src/app/creators/donate/top-donors.tsx
- apps/twitch-extension/src/app/components/widget.tsx
- apps/twitch-extension/src/app/config/page.tsx
- apps/twitch-extension/src/app/types.ts
Before upload to twitch update config.
Views:
> feat: remove CTA from twitch extension

- apps/twitch-extension/src/app/components/widget.tsx
- apps/twitch-extension/src/app/config/page.tsx
- apps/twitch-extension/src/app/layout.tsx
> fix: load twitch helper before other files

- apps/main-landing/src/app/creators/donate/page.tsx
- apps/main-landing/src/app/creators/donor/[address]/page.tsx
> fix: update creators navbar

- apps/main-landing/src/app/creators/donate/components/leaderboard/leaderboard-item.tsx
> fix: leaderboard placeholder bug

- apps/creator-api/routes/siwe.ts
- apps/main-landing/src/app/creators/donate/components/donate-form/donate-form.tsx
Fixes issues on prompting wallet linking for anon users on donate page, and SIWE failing on linking bc of ... INSERT REASON ...
> fix: Do not prompt for linking if anon on donate page. Fix verify endpoint failing.

- apps/creator-api/db/migrations/1757432868000-FixCreatorAddressSequence.ts
- apps/main-landing/src/app/creators/[name]/donate-page-avatar-menu.tsx
- apps/main-landing/src/app/creators/components/top-bar/desktop/desktop.tsx
- apps/main-landing/src/app/creators/context/auth-context.tsx
- apps/main-landing/src/app/creators/donate/donate-options-modal.tsx
- apps/main-landing/src/app/creators/hooks/use-logout.ts
- apps/main-landing/src/app/creators/privy-auth-sync.tsx
Fixes two things:
- Anon/Get recognized options modal flash showing after chosing to get recognized and redirecting back from twitch login
- Login state was not being remembered through browser reloads/restarts.
It does this by using localStorage for the donate option chosen (anon/get recognized) and also settinig the donor info to state if there is a session present and the option chosen is "get ercognized" (moved this to outer component) . Logout clears this localstorage key. 
Adds:
- My stats & history option on avatar menu on donate page.
Also includes some code comments for clarification
> Fix: donate options modal flash and login/logout not remembered

- apps/main-landing/src/app/creators/components/top-bar/desktop/desktop.tsx
- apps/main-landing/src/app/creators/donate/components/donate-form/donate-form.tsx
Removes one piece of unnecesary session setting. Add logs to find the cause of session not persistent [to be removed].
> test: Log Privy session to console. Remove setting creator on donate page

- apps/main-landing/src/app/creators/donate/components/donate-form/components/collectible-gallery.tsx
- apps/main-landing/src/app/creators/donate/donate-options-modal.tsx
- packages/ui/src/components/numeric-button-group/numeric-button-group.tsx
Fixes:
- Dynamic button on donate options modal (QA 171)
- Add ScrollArea to gallery (QA 172)
- Multiselector width jumping on value change (QA173)
> Fix: Multiple UI QAs on donate page

- apps/creator-api/utils/calculate-balances.ts
- apps/creator-api/utils/price-fetchers.ts
- apps/main-landing/src/app/creators/donate/components/donate-history/donate-history-item.tsx
- apps/main-landing/src/app/creators/utils/index.ts
1) fix opensea price estimation
2) fix url for not metadata as explained by the // team (id needs to be hex instead of number when the url has `/tokens/`)
3) remove `1` display when sending 1 not on history items
> fix nft metadata fetcher and amount display on history items

- apps/creator-api/utils/calculate-stats.ts
- apps/main-landing/src/app/creators/app/earnings/stats-and-history/page.tsx
- apps/main-landing/src/app/creators/app/profile/page.tsx
- apps/main-landing/src/app/creators/donate/components/donate-form/donate-form.tsx
- apps/main-landing/src/app/creators/donate/donate-options-modal.tsx
- apps/main-landing/src/app/creators/donate/hooks/use-link-wallet-if-needed.ts
Includes fixes: QAs 181, 124, 183 (donate options modal opening multiple times), and 187 (login issue)
> Fix: Daniel qas 9
