idriss-xyz/core

src/common/pageManagers/twitterPageManager.js
src/common/utils.js

As the IDriss icon is appended to the name element on Twitter, clicking it will open the profile of a user. On mobile, hovering the mouse like on pc is not possible. Hence, sending transactions is only possible when visiting someone's profile (and not from the context of a tweet). This PR fixes this issue by making the name link non-clickable on mobile screens. The profile can still be visited by clicking on the profile picture.

twitter names on mobile are not clickable anymore

---

src/application/agora/hooks/use-proposals-query.ts
src/application/agora/widgets/proposal-main.container.tsx
src/application/snapshot/hooks/use-proposals-query.ts
src/application/snapshot/widgets/organization-proposals.container.tsx
src/application/tally/hooks/use-proposals-query.ts
src/application/tally/widgets/organization-proposals.container.tsx
src/final/hooks/use-prefetch-proposals.ts
src/final/widgets/proposals/organisation-proposals.tsx

- Restored isPlaceholderData prop to prevent proposal widgets from disappearing when loading the next proposal.
- Updated the active proposals source for the proposal widgets layer. The previous configuration contained a bug where the Agora widget would appear for users without any widget (as the first available) due to prefetching.
- Lowered inactive tab 
https://github.com/user-attachments/assets/35ac43ae-95ad-4981-a1ad-5cff5504c55e

Restore proposals query placeholder data prop

---

apps/main-landing/src/app/creators/page.tsx

Fixes early error returns when typing an ENS or address manually.
The validation method on the form (from react-hook-form) was changed from onChange to onSubmit, meaning every field of the form gets validated after clicking the "DONATION LINK" button (submitting the form).
There was also an extra check for typed ENS names ending with a dot '.' that awas added to avoid present errors on calling resolver on them.  
[x] I have tested the functionality

fix(creators): Avoid early error feedback from ENS resolving.

---

apps/main-landing/src/app/creators/donate/hooks/use-native-transaction.ts

Donating in native currency was failing with error `out of gas`, as seen in: https://optimistic.etherscan.io/tx/0xa5d0fecaab957847177514c085c03ea148febaf83e9652e51bb9b82d93adee4d
I had mistakenly avoided the value in the gas estimate before sending the transaction. Added it back in this commit.
Send any native currency donation with any amount on any chain. It should work.

fix: out of gas native donations

---

apps/extension/src/host/warpcast/scraper.ts

This update refines the scraping methods to adapt to Warpcast's HTML/CSS changes, ensuring reliable extraction of usernames and recast usernames.
- replaced the previous CSS selector for scraping posts from warpcast with a more specific one, as warpcast's update to their HTML/CSS structure removed the ability to distinguish between usernames and recast usernames based on the tailwind font size classes
- updated the CSS selector to specifically target anchor tags with `font-semibold`, `hover:underline` tailwind classes and `data-idrissid` attribute, ensuring correct selection of both usernames and recast usernames
- refined the `getUserFromDirectCastConversation` method by adjusting element selection logic to accommodate warpcast’s updated structure. The updated method ensures proper …

fix: refine scraping methods for warpcast after their structural changes

---

apps/main-landing/src/components/token-section/hooks/use-geo-location.ts

This PR introduces a caching system to reduce repeated requests to geolocation APIs (ip-api and fallback geojs). Cached responses are stored in `localStorage` with a timestamp and validated against a defined expiration time (24 hours). If valid, the cached country is used, minimizing API calls and improving performance.

feat: add caching mechanism for geolocation API responses

---

apps/main-landing/src/components/footer/footer.tsx
apps/main-landing/src/components/products-section/components/desktop-products-section.tsx
apps/main-landing/src/components/products-section/components/product-section.tsx
apps/main-landing/src/components/token-section/components/index.ts
apps/main-landing/src/components/token-section/components/labeled-gradient-property.tsx
apps/main-landing/src/components/token-section/token-section.tsx

- rearranged token section layout according to new mockups and cleaned up afterwards
- fixed background hexagons overlap
- added lazy loading for tokenomics button

feat: rearranged token section layout

---

apps/extension/src/application/trading-copilot/subscriptions-management/subscriptions-management.tsx
apps/extension/src/application/trading-copilot/subscriptions-management/subscriptions-management.types.ts
apps/extension/src/final/extension-popup/extension-popup.tsx

Added verification if subscriptions refresh listener is already initialized to prevent multiple refreshes.

fix: initialize subscriptions refresh listener only once

---

apps/extension/src/final/notifications-popup/components/trading-copilot-dialog/trading-copilot-dialog.tsx
apps/extension/src/final/notifications-popup/components/trading-copilot-toast/trading-copilot-toast.tsx

- fixed idriss token icon svg initial size being too big (made it 24px x 24px according to mockups Figma)

fix: make idriss token icon smaller according to mockup

---

apps/copilot-api/routes/index.ts

Added handling of custom subscriberId in test swap to make testing easier. 
To send test-swap now we only need to fetch https://copilot-production-e887.up.railway.app/test-swap/{subscriberId} with method GET.
In subscriberId place we put our wallet address, method GET is default option - we can call this even by pasting URL in browser.
Example url with my wallet:
https://copilot-production-e887.up.railway.app/test-swap/0x8637AF884f71ef0e60851940E816dfE163599840

feat: add handling of subscriberId in test swap

---

apps/extension/src/application/trading-copilot/subscriptions-management/components/sound-toggle/sound-toggle.tsx
apps/extension/src/final/notifications-popup/components/trading-copilot-dialog/trading-copilot-dialog.tsx

- enabled notification sound (toggle in copilot) by default
- aligned trading-copilot-dialog component with mockup from figma (adjusted spacing above the title, X icon placement and it's color)

fix: enable notification sound by default and align copilot dialog with figma

---

apps/main-landing/src/components/footer/footer.tsx

- fix footer unclickable links in between lg and 4xl devices due to negative z-index

fix: footer unclickable links in between lg and 4xl devices

---

apps/extension/src/application/trading-copilot/commands/get-quote.ts
apps/extension/src/application/trading-copilot/hooks/use-exchanger.ts
apps/extension/src/application/trading-copilot/hooks/use-login-via-siwe.ts
apps/extension/src/application/trading-copilot/subscriptions-management/components/subscription-form.tsx
apps/extension/src/application/trading-copilot/subscriptions-management/components/subscriptions-list/subscription-item.tsx
apps/extension/src/application/trading-copilot/subscriptions-management/subscriptions-management.tsx
apps/extension/src/application/trading-copilot/subscriptions-management/subscriptions-management.types.ts
apps/extension/src/application/trading-copilot/types.ts
apps/extension/src/final/notifications-popup/components/trading-copilot-dialog/trading-copilot-dialog.tsx
apps/extension/src/final/notifications-popup/components/trading-copilot-dialog/trading-copilot-dialog.types.ts
apps/extension/src/final/widgets/follow-trading-copilot.tsx
apps/extension/src/infrastructure/application/providers.tsx
apps/extension/src/infrastructure/content-script/content-script.ts
apps/extension/src/shared/extension/auth-token-manager.ts
apps/extension/src/shared/extension/context/auth-token-context.tsx
apps/extension/src/shared/extension/context/index.ts
apps/extension/src/shared/extension/index.ts
apps/extension/src/shared/extension/types.ts
apps/extension/src/shared/web3/index.ts
apps/extension/src/shared/web3/storage.ts

Moved authToken from localStorage to context provider. Now we store authToken in extension context to have access to it across all tabs.
Updated /subscribe and /unsubscribe code to always have latest state of authToken.
Updated /get-quote in use-exchanger to also use latest state of authToken.

feat: move authToken from localStorage to context

---

apps/copilot-api/routes/index.ts

Changed since PRIME address was wrong (using mainnet 0xb23d80f5fefcddaa212212f028021b41ded428cf). New address is for DEGEN 0x4ed4e862860bed51a9570b96d89af5e1b0efefed, and conversion ratio was updated too (0.001 WETH to ~357 DEGEN)

fix(copilot): Change test-swap address to DEGEN on Base

---

apps/extension/src/application/trading-copilot/commands/get-tokens-list.ts
apps/extension/src/final/notifications-popup/notifications-popup.tsx
apps/extension/src/final/notifications-popup/utils/token-icon.tsx

Coingecko token list that we were using to fetch images and token symbols do not include tokens on the Base chain (which is the only chain we support not). This was refactored to use blockscout's specific Base token list, which has a little different format, thus some changes were required on `notifications-popup.tsx`.
Also added a check for when tokenImage (src string we use for the token icon displayed on the notification) is not present.

Fix: Current token list (coingecko) does not have Base tokens.

---

apps/extension/src/final/notifications-popup/components/trading-copilot-dialog/trading-copilot-dialog.tsx

We were getting error: `validateDOMNesting(...): <div> cannot appear as a descendant of <p>` when clicking on Copy and showing the copy trade modal/widget
Replaced the tags where TradingCopilotTooltip component was wrapped in paragraph `<p>` tags for `<div>` tags

fix(copilot): Tooltips cannot display div inside p

---

apps/extension/src/application/trading-copilot/commands/get-tokens-list.ts
apps/extension/src/final/notifications-popup/notifications-popup.tsx

Previous token list was too short on tokens (only had 50). This new one includes more than 800 tokens.
Used the new endpoint `https://li.quest/v1/tokens?chains=bas` (notice the filter with Base chain "chains=bas")
Execute any trade on a subscribed address on Jumper exchange with any Base token, it should reflect and see token icons on the IDRISS copilot notification. I tested $MISSER (token address `0x0718F45Bbf4781cE891e4e18182F025725F0fc95`)

Refactor: Use new copilot token list from LiFi

---

apps/extension/src/host/twitter/hooks/use-handle-to-username-map.ts

Extension was sending too many requests (sometimes in bratches of four) to api endpoint `/dao-twitter-handles`. Due to rate limits most times these requests are failing and retrying.
Added staleTime positive infinity like other requests and a retryDelay of 1 minute both in `use-handle-username-map.ts`, since this is not a time sensitive fetch or update. These are both parameters of useQuery from React, which is what our command abstraction is using under the hood.

fix: Repeated requests to dao-twitter-handles endpoint.

---

apps/main-landing/src/app/creators/obs/page.tsx
apps/main-landing/src/app/creators/obs/utils.ts

- support both ens names and hex addresses in the creator's OBS overlay page URL params
- add resolveEnsToHex utils function
- check both address and streamerAddress URL params (to handle legacy links)
https://github.com/user-attachments/assets/dd22c39b-1bff-4e12-8841-de6420562e51

feat: enable ens names in OBS page URL params 

---

apps/main-landing/.eslintrc.cjs
apps/main-landing/next.config.ts
apps/main-landing/src/app/creators/banner/page.tsx
apps/main-landing/src/app/creators/donate/components/chain-select.tsx
apps/main-landing/src/app/creators/donate/components/token-select.tsx
apps/main-landing/src/app/creators/donate/content.tsx
apps/main-landing/src/app/creators/donate/page.tsx
apps/main-landing/src/app/creators/obs/components/donation-notification.tsx
apps/main-landing/src/app/creators/page.tsx
apps/main-landing/src/components/footer/footer.tsx
apps/main-landing/src/components/hero-section/hero-section.tsx
apps/main-landing/src/components/image-sequencer/image-sequencer.tsx
apps/main-landing/src/components/products-section/components/product-section.tsx
apps/main-landing/src/components/superpowers-section/superpowers-section.tsx
apps/main-landing/src/components/token-section/hooks/use-geo-location.ts
apps/main-landing/src/components/token-section/token-section.tsx
apps/main-landing/src/components/top-bar/top-bar.tsx

Removed these warnings from running linter:
```
@idriss-xyz/main-landing:lint:fix: ./src/app/creators/obs/components/donation-notification.tsx
@idriss-xyz/main-landing:lint:fix: 49:7  Warning: Classname 'bg-opacity-80' should be replaced by an opacity suffix (eg. '/80')  tailwindcss/migration-from-tailwind-2
@idriss-xyz/main-landing:lint:fix: 54:9  Warning: Using `<img>` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
@idriss-xyz/main-landing:lint:fix: 61:26  Warning: Classname 'text-gray-900' is not a Tailwind CSS class!  tailwindcss/no-custom-classname …
```

fix: Linter warnings on donation-notification and use-geo-location

---

apps/extension/src/final/hooks/use-user-widgets.ts

Fixed problem with duplicated widgets. Fix work as expected on farcaster. We don't had any reports about same problem on twitter or supercast - but even if it did, it shouldn't happen from now.

fix: added filtering of duplicated users from scraper in widgets

---

apps/copilot-api/entities/subscribers.entity.ts
apps/copilot-api/entities/subscribtions.entity.ts
apps/copilot-api/routes/index.ts
apps/copilot-api/services/subscriptionManager.ts
apps/copilot-api/types/services.types.ts
apps/extension/src/application/trading-copilot/types.ts

Added authorization via secret key from env variables. We need to add token to .env variables and then pass it in url of test-swap.
My example url of test swap:
http://localhost:8080/test-swap/0x8637AF884f71ef0e60851940E816dfE163599840?secret=5ePj3e77NM
Added timestamp for subscribers and subscriptions in backend, and also passed it to frontend.

feat: authorize test-swap via secret key from env & add date timestamp for subscribers and subscriptions

---

apps/main-landing/src/app/claim/components/claim/claim-content.tsx
apps/main-landing/src/app/claim/components/not-eligible/not-eligible-content.tsx
apps/main-landing/src/components/token-section/components/geo-conditional-button.tsx

This PR addresses two issues present on design files on claim screen.
1. Buttons  "Buy on Uniswap" and "Buy on Jumper" were not spamming full different rows (they were in the same row).
2. There was no option to go back and check another wallet.

feat(airdrop): Add check different wallet, change eligible header

---

apps/main-landing/src/app/claim/components/vesting-plan/vesting-plan-content.tsx

- aligned spacings in that section to mockups
- made horizontal divider visible

fix: adjusted spacing around horizontal divider on the vesting plan page

---

apps/main-landing/src/app/claim/claim-page-context.tsx
apps/main-landing/src/app/claim/components/check-eligibility/check-eligibility-content.tsx
apps/main-landing/src/app/claim/components/claim-successful/claim-successful-content.tsx
apps/main-landing/src/app/claim/components/letter/letter-content.tsx
apps/main-landing/src/app/claim/components/not-eligible/not-eligible-content.tsx

- bring back flex-row in not eligible page
- geo block the first button on the claim page
- check if has already claimed and display accordingly on the claim-successful page
- add hasAlreadyClaimed to context, save it and use it

fix: updated after review

---

apps/main-landing/src/app/claim/components/vesting-plan/vesting-plan-content.tsx
apps/main-landing/src/app/vault/components/stake-tab-content.tsx
apps/main-landing/src/app/vault/components/unstake-tab-content.tsx
apps/main-landing/src/app/vault/content.tsx

- pass only number without commas in unstake handleSubmit
- removed the default 1 in staking and unstaking inputs
- replaced dashes with em dashes
- aligned icons in vault benefits section

fix: pass only number without commas in unstake handleSubmit

---

apps/main-landing/src/app/vault/content.tsx

- made spacing smaller on vault page

fix: update spacing on vault page

---

apps/main-landing/src/components/token-section/token-section.tsx

- added missing space in token section on mobile

fix: added missing space in token section on mobile

---

apps/main-landing/src/app/claim/components/about-idriss/about-idriss-content.tsx
apps/main-landing/src/app/claim/components/check-eligibility/check-eligibility-content.tsx
apps/main-landing/src/app/claim/components/claim/claim-content.tsx
apps/main-landing/src/app/claim/components/letter/letter-content.tsx
apps/main-landing/src/app/claim/components/vesting-plan/vesting-plan-content.tsx
apps/main-landing/src/app/vault/content.tsx

- replaced all usages of `ArrowRight` from `lucide-dev` library with our custom icon named `IdrissArrowRight` on /claim and /vault pages

fix: replace icons with our custom idriss arrow

---

apps/main-landing/src/app/claim/components/claim-successful/claim-successful-content.tsx

Before:
After:
This is a potential fix. However, due to the lack of specific information about the browser type and version, it has not been fully tested. I believe older versions of certain browsers may have issues rendering it correctly. For example, in my version of Firefox, the code appeared as follows:

fix: display amount of claimed tokens as one string

---

apps/extension/src/final/notifications-popup/components/trading-copilot-dialog/trading-copilot-dialog.tsx

- input for the amount in copilot dialog was displayed as not full width, this will set the correct width for it according to mockups in figma

fix: set correct input width in copilot dialog

---

apps/extension/package.json
apps/extension/rspack.config.mjs
pnpm-lock.yaml

Solana wallet is styled in the .css file similar to rainbowkit, so it will be beneficial for the future to have a loader that handles it

added css-loader

---

apps/extension/src/application/polymarket/commands/get-condition-id.ts
apps/extension/src/application/polymarket/constants.ts
apps/extension/src/application/polymarket/utils.ts

Fixed a type-check warning that was popping up locally and did not trigger ci on Github, but always triggered an error on local terminal. The error:
```
Argument of type 'Buffer' is not assignable to parameter of type 'Input'.
Type 'Buffer' is not assignable to type 'Uint8Array<ArrayBufferLike>'.
The types of 'slice(...).buffer' are incompatible between these types.
Type 'ArrayBufferLike' is not assignable to type 'ArrayBuffer'.
Type 'SharedArrayBuffer' is missing the following properties from type 'ArrayBuffer': resizable, resize, detached, transfer, transferToFixedLength
```
Created a new Uint8Array around the base64Secret which was Buffer type.

ci: Fix linter incompatible base64Secret type (Buffer)

---

apps/main-landing/src/components/products-section/components/prediction-markets-section/prediction-markets-section-actions.tsx

Updated styles to match figma designs.

fix: update styles for success and error message

---

packages/ui/src/components/icon/custom/coinmarketcap.tsx

fix: coinmarketcap icon size

---

packages/tailwind-config/tailwind.config.mjs

Fixes an issue with margin for containers on 4xl screens (from 1696px width).
Changed maxWidth attribute for 4xl screens on tailwind config

fix: Margin on 4xl screens (change maxWidth)

---

apps/main-landing/src/app/creators/obs/hooks/use-donation-notification.ts

Fixes an issue where if the sfx audio failed to play then the alert sound did not play either.
Added a way to return a boolean on play audio: true if it succedds and false if not, and if false then go ahead and play the alert sound.
TTs plays regardless of sfx failing. Alert should never fail since sound is a local file

fix: Play alert sound if sfx fails

---

apps/main-landing/src/app/creators/layout.tsx
apps/main-landing/src/app/creators/page.tsx

Creators og image was displaying only when navigating to /creators, but regular og image was displaying on sub routes (like /creators/app or /creators/[name]).
Added a layout file for the creators folder, that inherits main landing page metadata and overwrites some properties including og image. Sub routes then inherit these metadata properties and show the correct og-image

fix: Use creator og image on all sub routes of /creators

---

apps/main-landing/src/app/creators/app/form.tsx

Solves #560
On reading creator profile info from db and setting the values on the form, added a check that if the arrays for tokens or chains are empty then use all tokens or all chains constants. Now it correctly shows as all selected on creators/app and creators/[name]

fix: Empty networks and tokens don't show default list on creator-profile form

---

apps/main-landing/src/app/creators/app/earnings/layout.tsx
apps/main-landing/src/app/creators/app/layout.tsx
apps/main-landing/src/app/creators/app/profile/page.tsx
apps/main-landing/src/app/creators/app/ranking/layout.tsx
apps/main-landing/src/app/creators/app/setup/layout.tsx
apps/main-landing/src/app/creators/hooks/use-redirect-not-authenticated.ts

Fixes a potential workaround the users had to enter and navigate the creators v2 app without being authenticated.
- Extracted the logic present in creators/app/layout (to redirect the users if privy session not present) to a new hook called use-redirect-not-authenticated
- Call this new hook in all other inner layouts (earnings, setup, profile and ranking) so in case the user is able to click and navigate to them they are still redirected back to creators/login screen

fix: Redirect back to creators if not authenticated (QA 82)

---

apps/main-landing/src/app/creators/app/setup/payment-methods/page.tsx
packages/ui/src/components/switch/switch.tsx
packages/ui/src/components/toggle/toggle.tsx

Solves QA 89. If we want them back just remove the switchClassname hidden property. Also iconsrow position should have some padding to appear on the side.
Original:
After solving:

fix: Hide toggles on payment-methods tab of setup dashboard (QA 89)

---

apps/main-landing/src/app/creators/donate/components/donate-form/donate-form.tsx

fix: TTS label dissapears from donate form on legacy links

---

apps/main-landing/src/app/creators/app/earnings/stats-and-history/page.tsx
packages/ui/src/components/icon/constants.ts

fix: Change from custom Users icon to Lucide (Users2)

---

apps/main-landing/src/app/creators/app/layout.tsx
apps/main-landing/src/app/creators/app/setup/payment-methods/page.tsx

Fixes QA 101
payment methods fixes

fix: Remove some fiat icons. Truncate text (QA 101)

---

apps/main-landing/src/app/creators/app/earnings/balance/page.tsx
apps/main-landing/src/app/creators/app/earnings/stats-and-history/page.tsx
apps/main-landing/src/app/creators/app/earnings/top-donors/page.tsx
apps/main-landing/src/app/creators/app/ranking/top-creators/page.tsx
apps/main-landing/src/app/creators/app/ranking/top-donors/page.tsx
apps/main-landing/src/app/creators/app/setup/payment-methods/page.tsx
apps/main-landing/src/app/creators/app/setup/stream-alerts/page.tsx

Solves QA 100:
fix skeletons / page loading sequence
example: I'm a returning user and I open Balance, I currently see skeletons --> empty state with "no donations yet" --> actual view with data. It should be skeletons --> actual view with data)
this applies to other pages with defined empty states as well (Stats and history, Top donors), i should not see the empty state as a transitional step, this is the job of skeletons

feat: Add early returns (to skeletons) before data loading (QA 100)

---

apps/creator-api/routes/siwe.ts
apps/main-landing/src/app/creators/donate/components/donate-form/donate-form.tsx

Solves an issue where donating with a wallet (even tho it was linked to the current connected donor on donate page) was showing error:

fix: Don't throw error when wallet linked to current donor on donate page

---

apps/creator-api/utils/calculate-balances.ts
apps/main-landing/src/app/creators/donation-overlay/hooks/use-donation-notification.ts
apps/main-landing/src/app/creators/donation-overlay/utils.ts

1) messages are prefixed with ` ` to distinguish donations in indexers. this results in empty sound translation with eleven labs. -> now returning null in case of empty message
2) default to balance 1 instead of 0 for erc1155

make it so that empty messages dont result in `yy` sound but stay empty

---

apps/main-landing/src/app/globals.css

Hides privy popup on signup from creators landing and from donate page (pending test on staging)
Added css overrides with `display:none` after checking the minified version of the library privy/react-auth and finding the modal headers "All set!" and "Welcome (to IDRISS Creators)"

fix: Hide privy popup on register from UI
